In [2]:
print("Hello");

Hello


In [3]:
import numpy as np

1.Basic Array Creations

In [ ]:
arr1=np.array([1,2,3,4,5,6]) # vector- 1-dimension
print(arr1)

[1 2 3 4 5 6]


In [6]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]]) # metric- multi-dimension
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2.Array Generation Function 

In [ ]:
arr3=np.arange(1,11) # generate array 
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr4=np.zeros(6) # vector
print(arr4)

[0. 0. 0. 0. 0. 0.]


In [ ]:
arr5=np.zeros((4,6)) # multidimension - 4 rows & 6 columns
print(arr5)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [15]:
arr6=np.ones(6)
arr7=np.ones((3,6))
print(arr6)
print(arr7)

[1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
arr8=np.linspace(1,10,5) # linspace- return evenly spaced numbers over a specified interval
print(arr8)

[ 1.    3.25  5.5   7.75 10.  ]


3.Random Generation Function 

In [ ]:
arr9=np.random.rand(10) # generate random numbers only between 0 and 1
print(arr9)

[0.6780122  0.48489234 0.0729524  0.18493621 0.33905494 0.82069525
 0.03969008 0.3047376  0.73572257 0.85520299]


In [ ]:
arr10=np.random.randn(10) # generate random numbers 
print(arr10)

[-0.26222404 -0.25955652  0.92057913  0.37351283  0.09581729 -2.64579369
 -2.13006992  2.1210437  -0.56033602  1.87229582]


In [ ]:
arr11=np.random.randint(10) # generate a single random number from 0 to given number
print(arr11)

1


In [ ]:
arr12=np.random.randint(10,20,10) # generate 10 random numbers 10 and 20
print(arr12)

[11 17 10 19 18 12 11 10 18 14]


4.Array Attributes 

In [4]:
arr13=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr13)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr13.shape # give dimensions of the array

(3, 3)

In [ ]:
arr13.size # total number of elements

9

In [26]:
arr13.dtype

dtype('int64')

5.Array Methods


In [ ]:
print(arr13) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(arr13.min())
print(arr13.max())


1
9


In [12]:
print(arr13.sum())

45


In [13]:
np.sum(arr13,axis=0)

array([12, 15, 18])

In [16]:
print(arr13.mean())
print(arr13.std())

5.0
2.581988897471611


6.Reshaping and Resizing

In [20]:
arr14=np.arange(1,31)
print(arr14)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [22]:
arr14=arr14.reshape(6,5)
print(arr14)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
