In [2]:
import numpy as np

1.Numpy Indexing And Slicing of Vectors 


In [5]:
arr1=np.arange(11,21)
print(arr1)

[11 12 13 14 15 16 17 18 19 20]


In [6]:
arr1[1:5]

array([12, 13, 14, 15])

In [7]:
arr1[2:9:2]

array([13, 15, 17, 19])

2.Numpy Indexing and Slicing of Matrix

In [12]:
arr2=np.arange(1,31).reshape(6,5)
print(arr2)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [ ]:
print(arr2[5,4])   # Indexing

30


In [15]:
print(arr2[0:2,1:3])

[[2 3]
 [7 8]]


In [16]:
print(arr2[3:5,3:5])

[[19 20]
 [24 25]]


3.Boolean Indexing

In [20]:
arr3=np.arange(11,21)
print(arr3)

[11 12 13 14 15 16 17 18 19 20]


In [21]:
bool_Index=arr3%2==0
print(bool_Index)

[False  True False  True False  True False  True False  True]


In [22]:
arr4=arr3[bool_Index]
print(arr4)

[12 14 16 18 20]
