In [2]:
import numpy as np

1.Arithmatic Operations

In [5]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [ ]:
a1+a2 # size must be same

array([ 7,  9, 11, 13, 15])

In [10]:
a1-a2

array([-5, -5, -5, -5, -5])

In [11]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [12]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [13]:
a1//a2

array([0, 0, 0, 0, 0])

2.Broadcasting


In [15]:
arr1=np.array([10,20,30,40])
arr1+10

array([20, 30, 40, 50])

3.Deep and shallow copy

In [17]:
a=np.arange(1,20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [21]:
a_slice=a[0:6]
a_slice

array([1, 2, 3, 4, 5, 6])

4.Matrix Operations

In [29]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [ ]:
A @ B  # Matrix multiplication-

array([[19, 22],
       [43, 50]])

In [ ]:
A.T # Transpose

array([[1, 3],
       [2, 4]])

5.Advance Array Manuplation

In [32]:
#1. Stacking Arrays-
A=np.array([1,2,3,4])
B=np.array([5,6,7,8])

In [33]:
np.vstack((A,B))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
np.hstack((A,B))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
np.column_stack((A,B))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [37]:
# Splitting Arrays
c=np.arange(16).reshape(4,4)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [38]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [39]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]